service: mj-global-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::GlobalTable
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        Replicas:
          - Region: us-east-1
            PointInTimeRecoverySpecification:
              PointInTimeRecoveryEnabled: true
          - Region: us-east-2
            PointInTimeRecoverySpecification:
              PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        SSESpecification:
          SSEEnabled: true
          SSEType: KMS
  Outputs:
    NotesTableName:
      Value: !Ref NotesTable
      Export:
        Name: NotesTableName
    NotesTableArn:
      Value: !GetAtt NotesTable.Arn
      Export:
        Name: NotesTableArn
